---
title: "ESM 244 Lab 1"
author: "Jaenna Wessling"
date: "2023-01-13"
output: html_document
---

```{r setup, include=FALSE, echo = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(sf)
library(tmap)
```

```{r}
# Reading in our trees data (use read_csv for more options - better than read.csv)
sf_trees <- read_csv(here('data', 'sf_trees', "sf_trees.csv"), 
                     show_col_types = FALSE)

# Always inspect the data first 
summary(sf_trees)
names(sf_trees)


# Viewing the top 5 most common legal statuses and their respective tree count numbers 
top_5_status <- sf_trees %>% 
  group_by(legal_status) %>% 
  summarize(tree_count = n()) %>% 
  slice_max(tree_count, n = 5) %>% # just keeps the maximum/largest values of the number of top observations we want 
  arrange(-tree_count) # arranges selected choices from greatest to least 
```


# Creating a GG Plot of Top 5 SF trees legal status data 
```{r}
ggplot(data = top_5_status, aes(x = fct_reorder(legal_status, tree_count), y = tree_count)) + 
       # fct_reorder - reorders legal statuses from default alphabetical order to lowest - the greatest tree count
  geom_col() + 
  labs(y= 'Tree Count', x = 'Legal Status') + 
  coord_flip() + # flips the axes 
  theme_minimal()
```

### Keep obs where legal status is "Permitted Site" and caretaker is "MTA"
```{r}
# sf_trees$legal_status %>% unique()
permitted_mta <- sf_trees %>% 
  filter(legal_status == "Permitted Site" & caretaker =="MTA")
```

### Keep Blackwood acacia trees, only legal_status, date, latitude, longitude columns 
```{r}
blackwood_acacia <- sf_trees %>% 
  filter(str_detect(species, "Blackwood Acacia")) %>% 
  select(legal_status, date, latitude, longitude)

# Make a plot of SF acacia 
ggplot(data = blackwood_acacia, aes(x = longitude, y = latitude)) +
  geom_point()
```

